relativeURLs = true
title = "AFRAS SIAL"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbioline1 = "Economics PhD Student,"
    shortbioline2 = "University of California, Berkeley"
    logo = "ays.jpg"
