relativeURLs = true
title = "Afras Sial"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Economics PhD Student, University of California, Berkeley"
    logo = "ays.jpg"
